apiVersion: v1
kind: Pod
metadata:
  name: my-webserver
  labels:
     app: web
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
  - name: wavefront
    image: telegraf:1.9
